baseurl: /saopaulo
permalink: pretty
future: true
markdown: kramdown
paginate: 5
repo: saopaulo
github_org: maptime
maptime:
  chapter: MaptimeSP
  twitter: TwitterHandle
  #disqus: YOUR DISQUS USERNAME

gems:
  - jekyll-feed
